name: "Safe string generation"
description: "Convert a string into shortern and remove unsafe characters"
inputs:
  original:
    description: "Original string (such as branch name) to make safe for tag usage etc"
    required: true
  suffix:
    description: "Directory where terraform will be run from. Looks for versions.tf file in this path."
    default: ""
  length:
    description: "If set, trim the string to this length"

outputs:
  original:
    description: "Original string"
    value: ${{ steps.make_safe.outputs.original }}
  suffix:
    description: "Original suffix"
    value: ${{ steps.make_safe.outputs.suffix }}
  length:
    description: "Originally requested length"
    value: ${{ steps.make_safe.outputs.length }}
  safe:
    description: "Alphanumeric, lowercase, full length version of the original string."
    value: ${{ steps.make_safe.outputs.alphanumeric }}
  trimmed:
    description: "Trimmed version of the `safe` output string"
    value: ${{ steps.make_safe.outputs.trimmed }}

runs:
  using: "composite"
  steps:
    - id: make_safe
      shell: bash
      run: |
        str="${{inputs.original}}"
        suffix="${{inputs.suffix}}"
        max_len="${{inputs.length}}"
        suffix_len="${#suffix}"

        parsed=$(echo ${str} | tr '[:upper:]' '[:lower:]')
        safe=$( echo "${parsed}" | tr -cd '[:alnum:]')
        trimmed=""

        if [ ! -n "${{ inputs.length }}" ]; then
          sub_len="$((max_len - suffix_len))"
          trimmed=${safe:0:$sub_len}${suffix}
        fi

        echo "original=${str}"
        echo "suffix=${suffix}"
        echo "length=${max_len}"
        echo "safe=${safe}"
        echo "trimmed=${trimmed}"

        echo "original=${str}" >> $GITHUB_OUTPUT
        echo "suffix=${suffix}" >> $GITHUB_OUTPUT
        echo "length=${max_len}" >> $GITHUB_OUTPUT
        echo "safe=${safe}" >> $GITHUB_OUTPUT
        echo "trimmed=${trimmed}" >> $GITHUB_OUTPUT
