name: "[Pull Request] Workflow"

on:
  pull_request:
    branches: [main]

jobs:
  lint_yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/workflows/*.yml
  # generate branch name
  branch_name:
    needs: [lint_yaml]
    name: "Branch name"
    uses: ./.github/workflows/data-parse-branch-name.yml
    secrets: inherit
  # generate semver tag
  semver_tag:
    needs: [lint_yaml, branch_name]
    name: "Tag Name [${{ needs.branch_name.outputs.parsed }}]"
    uses: ./.github/workflows/data-parse-semver-tag.yml
    with:
      branch_name: ${{ needs.branch_name.outputs.parsed }}
    secrets: inherit
  # Generate a release
  create_draft_release:
    name: Create Release
    runs-on: 'ubuntu-latest'
    needs: [semver_tag]
    steps:
      - id: create_release
        name: "Create release"
        uses: ncipollo/release-action@v1.13.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ needs.semver_tag.outputs.new_tag }}
          name: ${{ needs.semver_tag.outputs.new_tag }}
          draft: true
          prerelease: true
          generateReleaseNotes: true
      - name: "Summary"
        id: summary
        run: |
          echo "### PR Information" >> $GITHUB_STEP_SUMMARY
          echo "| Variable | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| tag_name | ${{ needs.semver_tag.outputs.new_tag }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| release_name | ${{ needs.semver_tag.outputs.new_tag }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| draft | true |"  >> $GITHUB_STEP_SUMMARY
          echo "| prerelease | true |"  >> $GITHUB_STEP_SUMMARY
          echo "| release url | [${{ steps.create_release.outputs.id }}](${{ steps.create_release.outputs.html_url }}) |"  >> $GITHUB_STEP_SUMMARY
