name: "[Pull Request] Workflow"

on:
  pull_request:
    branches: [main]

jobs:
  lint_yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/workflows/*.yml
