name: "[Pull Request] Workflow"

on:
  pull_request:
    branches: [main]

jobs:
  lint_yaml:
    name: "Lint YAML"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/workflows/*.yml
  # generate branch name
  branch_name:
    needs: [lint_yaml]
    name: "Branch name"
    uses: ./.github/workflows/data-parse-branch-name.yml
    secrets: inherit

  # generate semver tag
  semver_tag:
    needs: [lint_yaml, branch_name]
    name: "Tag [${{ needs.branch_name.outputs.branch_name }}]"
    uses: ./.github/workflows/data-parse-semver-tag.yml
    with:
      branch_name: ${{ needs.branch_name.outputs.branch_name }}
    secrets: inherit
  # Output summary data
  summary:
    if: always()
    name: PR
    runs-on: 'ubuntu-latest'
    needs: [branch_name, semver_tag]
    steps:
      - id: summary
        name: "Summary"
        run: |
          echo "### PR Information" >> $GITHUB_STEP_SUMMARY
          echo "| Segment | Variable | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| Branch | branch_name | ${{ needs.branch_name.outputs.branch_name }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| Branch | Safe | ${{ needs.branch_name.outputs.safe }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| Branch | Full Length | ${{ needs.branch_name.outputs.full_length }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| Semver | Tag | ${{ needs.semver_tag.outputs.tag }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| Semver | New Tag | ${{ needs.semver_tag.outputs.new_tag }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| Semver | Pre-release | ${{ needs.semver_tag.outputs.prerelease }} |"  >> $GITHUB_STEP_SUMMARY

  end:
    name: 'End of PR workflow'
    runs-on: 'ubuntu-latest'
    needs: [branch_name, semver_tag, summary]
    steps:
      - id: end
        name: End
        run: |
          echo "End"
