name: "[Pull Request] Workflow"

on:
  pull_request:
    branches: [main]

jobs:
  lint_yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/workflows/*.yml
  # generate branch name
  branch_name:
    needs: [lint_yaml]
    name: "Branch name"
    uses: ./.github/workflows/data-parse-branch-name.yml
    secrets: inherit
  # generate semver tag
  semver_tag:
    needs: [lint_yaml, branch_name]
    name: "Tag Name (${{ needs.branch_name.outputs.parsed }})"
    uses: ./.github/workflows/data-parse-semver-tag.yml
    with:
      branch_name: ${{ needs.branch_name.outputs.parsed }}
    secrets: inherit
  # Generate a release
  create_draft_release:
    name: Create Release
    runs-on: 'ubuntu-latest'
    needs: [semver_tag]
    steps:
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.semver_tag.outputs.tag }}
          release_name: ${{ needs.semver_tag.outputs.tag }}
          draft: true
          prerelease: true
