name: "[Pull Request] TEST"

on:
  pull_request:
    branches: [main]

jobs:

  # Output summary data
  test:
    name: TEST
    runs-on: 'ubuntu-latest'
    steps:
      - id: version
        name: Get version
        uses: ministryofjustice/opg-github-actions/.github/actions/terraform-version@test-tag
