name: "[Pull Request] TEST"

on:
  pull_request:
    branches: [main]

permissions:
  contents: write
  security-events: none
  pull-requests: none
  actions: read
  checks: none
  deployments: read
  issues: read
  packages: none
  repository-projects: none
  statuses: none


jobs:

  # Output summary data
  asStep:
    name: TEST STEP
    runs-on: 'ubuntu-latest'
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: version
        name: Get version
        uses: ministryofjustice/opg-github-actions/.github/actions/terraform-version@v2.8.0-goversion.0 #test-tag
        with:
          github_token: ${GH_TOKEN}
  # asWorkflow:
  #   name: TEST WORKFLOW
  #   uses: ./.github/workflows/data-parse-test-terraform-version.yml
  #   with:
  #     terraform_directory: "./"
  #   secrets: inherit
