name: "[Analysis - Infrastructure] TFSec To Github Security"

on:
  workflow_call:


permissions:
  security-events: write
  actions: read
  checks: read
  contents: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none

jobs:
  tfsec_analysis_to_github_security:
    name: TFSec static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 2
      - name: Run tfsec
        uses: aquasecurity/tfsec-sarif-action@21ded20e8ca120cd9d3d6ab04ef746477542a608 # v0.1.4
        with:
          sarif_file: tfsec.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@ce28f5bb42b7a9f2c824e633a3f6ee835bab6858 # v3.29.0
        with:
          sarif_file: tfsec.sarif
