name: "[Analysis - Infrastructure] TFSec Pull Request Feedback"

on:
  workflow_call:
    inputs:
      terraform_path:
        description: 'String containing a JSON formated list of relative directory paths where terraform files would exist.'
        type: string
        default: '["terraform/account", "terraform/environment"]'
      soft_fail:
        description: 'Set to true to to comment silently without breaking the build'
        type: boolean
        default: false
      job_strategy_fail_fast:
        description: 'When true, GitHub will cancel all in-progress and queued jobs in the matrix if any job in the matrix fails'
        type: boolean
        default: false
    secrets:
      source_github_token:
          required: true

permissions:
  actions: read
  checks: read
  contents: none
  deployments: none
  issues: none
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  tfsec_pr_commenter:
    name: TFSec static analysis pull request feedback
    runs-on: ubuntu-latest
    strategy:
      fail-fast: ${{ inputs.job_strategy_fail_fast }}
      matrix:
        terraform_path: ${{ fromJSON(inputs.terraform_path) }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: tfsec with pr comments
        uses: aquasecurity/tfsec-pr-commenter-action@v1.3.0
        with:
          soft_fail_commenter: ${{ inputs.soft_fail }}
          working_directory: ${{ matrix.terraform_path }}
          github_token: ${{ secrets.source_github_token }}
