name: "[Analysis - Infrastructure] TFSec Pull Request Feedback"

on:
  workflow_call:
    inputs:
      terraform_path:
        description: "String containing a JSON formated list of relative directory paths where terraform files would exist."
        type: string
        default: '["terraform/account", "terraform/environment"]'
      soft_fail:
        description: "Set to true to to comment silently without breaking the build"
        type: boolean
        default: false
      job_strategy_fail_fast:
        description: "When true, GitHub will cancel all in-progress and queued jobs in the matrix if any job in the matrix fails"
        type: boolean
        default: false
    secrets:
      source_github_token:
        required: true

permissions:
  actions: read
  checks: read
  contents: none
  deployments: none
  issues: none
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  config_summary:
    name: "Config"
    runs-on: ubuntu-latest
    steps:
      - name: Summary
        if: always()
        run: |
          echo "### TFSec Pull Request Config" >> $GITHUB_STEP_SUMMARY
          echo "| Option | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| terraform_path | ${{ inputs.terraform_path }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| soft_fail | ${{ inputs.soft_fail }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| job_strategy_fail_fast | ${{ inputs.job_strategy_fail_fast }} |"  >> $GITHUB_STEP_SUMMARY

  tfsec_pr_commenter:
    name: TFSec static analysis pull request feedback
    runs-on: ubuntu-latest
    strategy:
      fail-fast: ${{ inputs.job_strategy_fail_fast }}
      matrix:
        terraform_path: ${{ fromJSON(inputs.terraform_path) }}
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 2
      - name: tfsec with pr comments
        uses: aquasecurity/tfsec-pr-commenter-action@7a44c5dcde5dfab737363e391800629e27b6376b # v1.3.1
        with:
          soft_fail_commenter: ${{ inputs.soft_fail }}
          working_directory: ${{ matrix.terraform_path }}
          github_token: ${{ secrets.source_github_token }}
