name: "[Build - Containers] Build Docker Container"

on:
  workflow_call:
    inputs:
      image_data:
        description: 'String containing a JSON formated list of directories to build from. Exclude the trailing slash. For example: [{"name":"test", "directory": "./app"}] .'
        type: string
        required: true
      formatted_build_command:
        description: 'A format() compatible string that will be used as the docker build command. {0} = name'
        type: string
        default: 'docker build -t {0}:latest .'
      job_strategy_fail_fast:
        description: 'When true, GitHub will cancel all in-progress and queued jobs in the matrix if any job in the matrix fails'
        type: boolean
        default: false

permissions:
  contents: read
  security-events: none
  pull-requests: none
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none

jobs:
  docker_build:
    name: "Docker build"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: ${{ inputs.job_strategy_fail_fast }}
      matrix:
        image: ${{ fromJSON(inputs.image_data) }}
    defaults:
      run:
        working-directory: ${{ matrix.image.directory }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build
        env:
          cmd: ${{ format( inputs.formatted_build_command, matrix.image.name ) }}
        run: |
          echo "Build command: ${{ env.cmd }}"
          ${{ env.cmd }}
