# Generate Terraform Workspace name
name: "[Data - Parse] Terraform Workspace Name"

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      name:
        description: 'Generated terraform workspace name.'
        value: ${{ jobs.generate_workspace_name.outputs.workspace_name }}

permissions:
  contents: read
  security-events: none
  pull-requests: none
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none

jobs:
  generate_workspace_name:
    name: 'Generate the terraform workspace name to use'
    runs-on: ubuntu-latest
    outputs:
      workspace_name: ${{ steps.workspace_name.outputs.workspace_name }}
    steps:
      - id: workspace_name
        name: Generate
        run: |
          # Use the source branch name if this is a pull request
          if [ -z "${GITHUB_HEAD_REF}" ]; then
            branch=${GITHUB_REF#refs/heads/}
          else
            branch=${GITHUB_HEAD_REF}
          fi
          echo "BRANCH: ${branch}"

          if [ "${branch}" == "main" ]; then
            workspace_name="production"
          else
            branch=${branch::10}
            workspace_name="${branch}${{ github.event.number }}"
            workspace_name=${workspace_name//-}
            workspace_name=${workspace_name//_}
            workspace_name=${workspace_name//\/}
            workspace_name=${workspace_name:0:11}
            workspace_name=$(echo ${workspace_name} | tr '[:upper:]' '[:lower:]')
          fi

          echo "workspace_name=${workspace_name}" >> $GITHUB_OUTPUT
          echo "WORKSPACE: ${workspace_name}"

  results:
    name: 'Results'
    runs-on: ubuntu-latest
    needs: [generate_workspace_name]
    steps:
      - name: 'Summary'
        if: always()
        run: |
          echo "### Workspace Name Results" >> $GITHUB_STEP_SUMMARY
          echo "| Variable | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| workspace_name | ${{ needs.generate_workspace_name.outputs.workspace_name }} |"  >> $GITHUB_STEP_SUMMARY
