# Return a semvar style tag based on the repos existing tags
name: "[Data - Parse] Semvar Tag"


on:
  workflow_call:
    outputs:
      tag:
        description: "Version Tag"
        value: ${{ jobs.create_tags.outputs.version_tag }}
    inputs:
      branch_name:
        type: string
        description: "Current Git branch name"
        required: true

jobs:
  create_tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bump version
        id: bump_version
        uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INITIAL_VERSION: 0.0.0
          DEFAULT_BUMP: minor
          PRERELEASE_SUFFIX: ${{ inputs.branch_name }}
          RELEASE_BRANCHES: main
          WITH_V: true
    outputs:
      version_tag: ${{ steps.bump_version.outputs.tag }}
