# Generate Branch Names from GITHUB data
name: "[Data - Parse] Branch Name"

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      push_to_github_env:
        description: 'Boolean to push the clean branch name into $GITHUB_ENV as $BRANCH_NAME'
        type: boolean
        default: true
        required: false
    outputs:
      raw:
        description: 'Raw branch name with slashes and other non alphanumeric chars left in place'
        value: ${{ jobs.extract.outputs.raw_branch }}
      parsed:
        description: 'Parsed branch name with some chars removed.'
        value: ${{ jobs.extract.outputs.parsed_branch }}
      alphanumeric:
        description: 'Parsed branch name with ONLY alphanumeric chars.'
        value: ${{ jobs.extract.outputs.alphanumeric_branch }}

permissions:
  contents: read
  security-events: none
  pull-requests: none
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none

jobs:
  extract:
    name: 'Use github data to generate a clean branch name'
    runs-on: ubuntu-latest
    outputs:
      raw_branch: ${{ steps.parse.outputs.raw_branch }}
      parsed_branch: ${{ steps.parse.outputs.parsed_branch }}
      alphanumeric_branch: ${{ steps.parse.outputs.alphanumeric_branch }}
    steps:
      - id: parse
        name: Parse branch name
        run: |

          branch=${GITHUB_REF#refs/heads/}

          if [ "${branch}" == "" ]; then
            raw_branch="main"
            parsed_branch="main"
            alphanumeric_branch="main"
          else
            raw_branch=${branch}
            parsed_branch=${branch//-}
            parsed_branch=${branch//_}
            parsed_branch=${branch//\/}
            alphanumeric_branch=$( echo "${raw_branch}" | tr -cd '[:alnum:]')
          fi
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB HEAD REF: ${{ github.head_ref }}"
          echo "RAW BRANCH: ${raw_branch}"
          echo "PARSED BRANCH: ${parsed_branch}"
          echo "ALPHANUMERIC BRANCH: ${alphanumeric_branch}"

          echo "::set-output name=raw_branch::${raw_branch}"
          echo "::set-output name=parsed_branch::${parsed_branch}"
          echo "::set-output name=alphanumeric_branch::${alphanumeric_branch}"

      - name: Push to GITHUB_ENV
        if: inputs.push_to_github_env
        run: |
          echo BRANCH_NAME=${{ steps.parse.outputs.parsed_branch }} >> $GITHUB_ENV
