# Generate Branch Names from GITHUB data
name: "[Data - Parse] Branch Name"

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      push_to_github_env:
        description: 'Boolean to push the clean branch name into $GITHUB_ENV as $BRANCH_NAME'
        type: boolean
        default: false
        required: false
    outputs:
      branch_name:
        description: The original branch name with output any modification.'
        value: ${{ jobs.branch_name.outputs.branch_name }}
      full_length:
        description: 'Alphanumeric, lowercase, but full length version of the original string.'
        value: ${{ jobs.branch_name.outputs.full_length }}
      safe:
        description: 'Alphanumeric and lowercase version of the original, trimmed to 12 characters.'
        value: ${{ jobs.branch_name.outputs.safe }}


permissions:
  contents: read
  security-events: none
  pull-requests: none
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none

jobs:
  config_summary:
    name: "Config"
    runs-on: ubuntu-latest
    steps:
      - name: Summary
        if: always()
        run: |
          echo "### Branch Name Config" >> $GITHUB_STEP_SUMMARY
          echo "| Option | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| push_to_github_env | ${{ inputs.push_to_github_env }} |"  >> $GITHUB_STEP_SUMMARY

  branch_name:
    name: 'Use github data to generate a clean branch name'
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.get_branch_name.outputs.branch_name }}
      safe: ${{ steps.get_branch_name.outputs.safe }}
      full_length: ${{ steps.get_branch_name.outputs.full_length }}
    steps:
      - id: get_branch_name
        name: Parse branch name
        uses: ministryofjustice/opg-github-actions/.github/actions/branch-name@v3.1.0
      - name: Push to GITHUB_ENV
        if: inputs.push_to_github_env
        run: |
          echo BRANCH_NAME=${{ steps.get_branch_name.outputs.full_length }} >> $GITHUB_ENV

  results:
    name: 'Results'
    runs-on: ubuntu-latest
    needs: [branch_name]
    steps:
      - name: 'Summary'
        if: always()
        run: |
          echo "### Branch Name Results" >> $GITHUB_STEP_SUMMARY
          echo "| Variable | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| branch_name | ${{ needs.branch_name.outputs.branch_name }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| full_length | ${{ needs.branch_name.outputs.full_length }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| safe | ${{ needs.branch_name.outputs.safe }} |"  >> $GITHUB_STEP_SUMMARY
