# Generate Branch Names from GITHUB data
name: "[Data - Parse] Branch Name"

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      push_to_github_env:
        description: 'Boolean to push the clean branch name into $GITHUB_ENV as $BRANCH_NAME'
        type: boolean
        default: true
        required: false
    outputs:
      original:
        description: The original branch name with output any modification.'
        value: ${{ jobs.extract.outputs.orginal }}
      safe:
        description: 'A lowercase version thats safe for tagging and similar containing only alphanumeric characters.'
        value: ${{ jobs.extract.outputs.safe }}
      trimmed:
        description: 'The safe value, but trimmed to 12 characters'
        value: ${{ jobs.extract.outputs.trimmetrimmedd_branch }}

permissions:
  contents: read
  security-events: none
  pull-requests: none
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none

jobs:
  config_summary:
    name: "Config"
    runs-on: ubuntu-latest
    steps:
      - name: Summary
        if: always()
        run: |
          echo "### Branch Name Config" >> $GITHUB_STEP_SUMMARY
          echo "| Option | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| push_to_github_env | ${{ inputs.push_to_github_env }} |"  >> $GITHUB_STEP_SUMMARY

  extract:
    name: 'Use github data to generate a clean branch name'
    runs-on: ubuntu-latest
    outputs:
      original: ${{ steps.parse.outputs.original }}
      safe: ${{ steps.parse.outputs.safe }}
      trimmed: ${{ steps.parse.outputs.trimmed }}
    steps:
      - id: branch_setup
        run: |
          branch=${GITHUB_HEAD_REF}
          if [ "${branch}" == "" ]; then
            branch="main"
          fi
          echo "branch=${branch}" >> $GITHUB_OUTPUT
      - id: parse
        name: Parse branch name
        uses: ministryofjustice/opg-github-workflows/.github/actions/safe-strings@comp-test
        with:
          original: ${{steps.branch_setup.outputs.branch}}
          length: 12
      - run: |
          echo "safe: [ ${{ steps.parse.outputs.safe}} ]"
      - name: Push to GITHUB_ENV
        if: inputs.push_to_github_env
        run: |
          echo BRANCH_NAME=${{ steps.parse.outputs.safe }} >> $GITHUB_ENV

  results:
    name: 'Results'
    runs-on: ubuntu-latest
    needs: [extract]
    steps:
      - name: 'Summary'
        if: always()
        run: |
          echo "### Branch Name Results" >> $GITHUB_STEP_SUMMARY
          echo "| Variable | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| original | ${{ needs.extract.outputs.original }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| safe | ${{ needs.extract.outputs.safe }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| trimmed | ${{ needs.extract.outputs.trimmed }} |"  >> $GITHUB_STEP_SUMMARY
