# Generate Branch Names from GITHUB data
name: "[Data - Parse] Branch Name"

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      push_to_github_env:
        description: 'Boolean to push the clean branch name into $GITHUB_ENV as $BRANCH_NAME'
        type: boolean
        default: true
        required: false
    outputs:
      raw:
        description: 'Raw branch name with slashes and other non alphanumeric chars left in place'
        value: ${{ jobs.extract.outputs.raw_branch }}
      parsed:
        description: 'Parsed branch name with some chars removed.'
        value: ${{ jobs.extract.outputs.parsed_branch }}
      alphanumeric:
        description: 'Parsed branch name with ONLY alphanumeric chars.'
        value: ${{ jobs.extract.outputs.alphanumeric_branch }}

permissions:
  contents: read
  security-events: none
  pull-requests: none
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none

jobs:
  config_summary:
    name: "Config"
    runs-on: ubuntu-latest
    steps:
      - name: Summary
        if: always()
        run: |
          echo "### Branch Name Config" >> $GITHUB_STEP_SUMMARY
          echo "| Option | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| push_to_github_env | ${{ inputs.push_to_github_env }} |"  >> $GITHUB_STEP_SUMMARY

  extract:
    name: 'Use github data to generate a clean branch name'
    runs-on: ubuntu-latest
    outputs:
      raw_branch: ${{ steps.parse.outputs.original }}
      parsed_branch: ${{ steps.parse.outputs.safe }}
      alphanumeric_branch: ${{ steps.parse.outputs.safe }}
      trimmed_branch: ${{ steps.parse.outputs.trimmed }}
    steps:
      - id: branch_setup
        run: |
          branch=${GITHUB_HEAD_REF}
          if [ "${branch}" == "" ]; then
            branch="main"
          fi
          echo "branch=${branch}" >> $GITHUB_OUTPUT
      - id: parse
        name: Parse branch name
        uses: ministryofjustice/opg-github-workflows/.github/actions/safe-strings.yml@v1.37.0-compositeactions.1
        with:
          original: ${{steps.branch_setup.outputs.branch}}
      - run: |
          echo "safe: [ ${{ steps.parse.outputs.safe}} ]"
      - name: Push to GITHUB_ENV
        if: inputs.push_to_github_env
        run: |
          echo BRANCH_NAME=${{ steps.parse.outputs.safe }} >> $GITHUB_ENV

  results:
    name: 'Results'
    runs-on: ubuntu-latest
    needs: [extract]
    steps:
      - name: 'Summary'
        if: always()
        run: |
          echo "### Branch Name Results" >> $GITHUB_STEP_SUMMARY
          echo "| Variable | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| raw_branch | ${{ needs.extract.outputs.raw_branch }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| parsed_branch | ${{ needs.extract.outputs.parsed_branch }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| alphanumeric_branch | ${{ needs.extract.outputs.alphanumeric_branch }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| trimmed_branch | ${{ needs.extract.outputs.trimmed_branch }} |"  >> $GITHUB_STEP_SUMMARY
