# Return a semver style tag based on the repos existing tags
name: "[Data - Parse] Semver Tag"


on:
  workflow_call:

    inputs:
      prerelease:
        description: "Flag to show if this is a pre-release"
        type: boolean
        default: true
      release_branch:
        type: string
        description: "Branch used for releases, defaults to main"
        default: "main"
        required: false
      releases_enabled:
        type: boolean
        description: "Enable creation of a release when appropriate."
        default: false
    outputs:
      truncated_branch_name:
        description: "Truncated branch name used for tag creation"
        value: ${{ jobs.create_tags.outputs.truncated_branch_name }}
      created_tag:
        description: "New Tag"
        value: ${{ jobs.create_tags.outputs.created_tag }}
      prerelease:
        description: "Flag to show if this was created as a pre-release"
        value: ${{ jobs.create_tags.outputs.prerelease }}

    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  config_summary:
    name: "Config"
    runs-on: ubuntu-latest
    steps:
      - name: Summary
        if: always()
        run: |
          echo "### Semver Config" >> $GITHUB_STEP_SUMMARY
          echo "| Option | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| prerelease | ${{ inputs.prerelease }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| releases_enabled | ${{ inputs.releases_enabled }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| release_branch | ${{ inputs.release_branch }} |"  >> $GITHUB_STEP_SUMMARY

  create_tags:
    name: "Create tags and release"
    runs-on: ubuntu-latest
    steps:
      - name: "Generate semver tag and release"
        id: semver_tag
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' }}
        uses: ministryofjustice/opg-github-actions/.github/actions/semver-tag@v2.3.3
        with:
          release_branch: ${{ inputs.release_branch }}
          prerelease: ${{ inputs.prerelease }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          releases_enabled: ${{ inputs.releases_enabled }}

    outputs:
      truncated_branch_name: ${{ steps.semver_tag.outputs.safe }}
      created_tag: ${{ steps.semver_tag.outputs.created_tag }}
      prerelease: ${{ steps.semver_tag.outputs.prerelease }}

  results:
    name: 'Results'
    runs-on: ubuntu-latest
    needs: [create_tags]
    steps:
      - name: Summary
        if: always()
        run: |
          echo "### Semver Results" >> $GITHUB_STEP_SUMMARY
          echo "| Variable | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| truncated_branch_name | ${{ needs.create_tags.outputs.truncated_branch_name }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| created_tag | ${{ needs.create_tags.outputs.created_tag }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| prerelease | ${{ needs.create_tags.outputs.prerelease }} |"  >> $GITHUB_STEP_SUMMARY
