# Find Terraform Version from the versions.tf file
name: "[Data - Parse] Terraform Version"
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      terraform_directory:
        type: string
        description: "Directory where terraform will be run from. Looks for versions.tf file in this path."
        required: true
      terraform_versions_file:
        type: string
        description: "Name of file that contains the required_version config is stored. (Default `./versions.tf`)"
        default: "./versions.tf"
    outputs:
      version:
        description: 'Discovered terraform version range. This may be an exact number (like 1.5.5) or a semver range (like >= 1.0).'
        value: ${{ jobs.discover_version_semver_range.outputs.version }}

permissions:
  contents: read
  security-events: none
  pull-requests: none
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none

defaults:
  run:
    shell: bash


jobs:
  config_summary:
    name: "Config"
    runs-on: ubuntu-latest
    steps:
      - name: Summary
        if: always()
        run: |
          echo "### Terraform Version Config" >> $GITHUB_STEP_SUMMARY
          echo "| Option | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| terraform_directory | ${{ inputs.terraform_directory }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| terraform_versions_file | ${{ inputs.terraform_versions_file }} |"  >> $GITHUB_STEP_SUMMARY

  find_version:
    name: "Find version [${{ inputs.terraform_versions_file }}]"
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version}}
    steps:
      - id: version
        name: Get version
        uses: ministryofjustice/opg-github-actions/.github/actions/terraform-version@v1.0.0
        with:
          terraform_directory: ${{inputs.terraform_directory}}
          terraform_versions_file: ${{inputs.terraform_versions_file}}


  results:
    name: "Results"
    runs-on: ubuntu-latest
    needs: [find_version]
    steps:
      - name: Summary
        if: always()
        run: |
          echo "### Terraform Version Results" >> $GITHUB_STEP_SUMMARY
          echo "| Option | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| version | ${{ needs.find_version.outputs.version }} |"  >> $GITHUB_STEP_SUMMARY
