# Return a semver style tag based on the repos existing tags
name: "[Data - Parse] Semver Tag"


on:
  workflow_call:
    outputs:
      tag:
        description: "Version Tag"
        value: ${{ jobs.create_tags.outputs.tag }}
      new_tag:
        description: "New Tag"
        value: ${{ jobs.create_tags.outputs.new_tag }}
    inputs:
      branch_name:
        type: string
        description: "Current Git branch name"
        required: true
      release_branch:
        type: string
        description: "Branch used for releases, defaults to main"
        default: "main"
        required: false

jobs:
  create_tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Bump version
        id: bump_version
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INITIAL_VERSION: 0.0.1
          DEFAULT_BUMP: minor
          PRERELEASE_SUFFIX: ${{ inputs.branch_name }}
          RELEASE_BRANCHES: ${{ inputs.release_branch }}
          WITH_V: true
    outputs:
      tag: ${{ steps.bump_version.outputs.tag }}
      new_tag: ${{ steps.bump_version.outputs.new_tag }}

  github_summary:
    name: 'Output data to Github Summary'
    runs-on: ubuntu-latest
    needs: [create_tags]
    steps:
      - name: Summary
        id: Summary
        run: |
          echo "### Semver Information" >> $GITHUB_STEP_SUMMARY
          echo "#### Inputs" >> $GITHUB_STEP_SUMMARY
          echo "| Variable | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| branch_name | ${{ inputs.branch_name }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| release_branch | ${{ inputs.release_branch }} |"  >> $GITHUB_STEP_SUMMARY
          echo "#### Outputs" >> $GITHUB_STEP_SUMMARY
          echo "| Variable | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| tag | ${{ needs.create_tags.outputs.tag }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| new_tag | ${{ needs.create_tags.outputs.new_tag }} |"  >> $GITHUB_STEP_SUMMARY
