# Return a semver style tag based on the repos existing tags
name: "[Data - Parse] Semver Tag"


on:
  workflow_call:
    outputs:
      truncated_branch_name:
        description: "Truncated version of inputs.branch_name"
        value: ${{ jobs.create_tags.outputs.truncated_branch_name }}
      tag:
        description: "Version Tag"
        value: ${{ jobs.create_tags.outputs.tag }}
      new_tag:
        description: "New Tag"
        value: ${{ jobs.create_tags.outputs.new_tag }}
      prerelease:
        description: "Flag to show if this was created as a pre-release"
        value: ${{ jobs.create_tags.outputs.prerelease }}
    inputs:
      branch_name:
        type: string
        description: "Current branch name. Used for tag creation, but trucated to 16 characters."
        required: true
      release_branch:
        type: string
        description: "Branch used for releases, defaults to main"
        default: "main"
        required: false

jobs:
  config_summary:
    name: "Config"
    runs-on: ubuntu-latest
    steps:
      - name: Summary
        if: always()
        run: |
          echo "### Semver Config" >> $GITHUB_STEP_SUMMARY
          echo "| Option | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| branch_name | ${{ inputs.branch_name }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| release_branch | ${{ inputs.release_branch }} |"  >> $GITHUB_STEP_SUMMARY

  create_tags:
    name: "Create tags"
    runs-on: ubuntu-latest
    steps:
      - id: truncate
        name: Truncate branch name
        uses: ministryofjustice/opg-github-actions/.github/actions/safe-strings@9698787723a6a964ef9816066d9299568d8d359e # v3.1.0
        with:
          original: ${{ inputs.branch_name }}
          length: 12
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: '0'
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
      - name: Create Tag
        id: create_tag
        uses: anothrNick/github-tag-action@a2c70ae13a881faf2b4953baaa9e49731997ab36 # 1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INITIAL_VERSION: 0.0.1
          DEFAULT_BUMP: minor
          PRERELEASE_SUFFIX: ${{ steps.truncate.outputs.safe }}
          PRERELEASE: ${{ inputs.branch_name != inputs.release_branch && true || false }}
          RELEASE_BRANCHES: ${{ inputs.release_branch }}
          WITH_V: true
    outputs:
      truncated_branch_name: ${{ steps.truncate.outputs.safe }}
      tag: ${{ steps.create_tag.outputs.tag }}
      new_tag: ${{ steps.create_tag.outputs.new_tag }}
      prerelease: ${{ inputs.branch_name != inputs.release_branch && true || false }}

  results:
    name: 'Results'
    runs-on: ubuntu-latest
    needs: [create_tags]
    steps:
      - name: Summary
        if: always()
        run: |
          echo "### Semver Results" >> $GITHUB_STEP_SUMMARY
          echo "| Variable | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| truncated_branch_name | ${{ needs.create_tags.outputs.truncated_branch_name }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| tag | ${{ needs.create_tags.outputs.tag }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| new_tag | ${{ needs.create_tags.outputs.new_tag }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| prerelease | ${{ needs.create_tags.outputs.prerelease }} |"  >> $GITHUB_STEP_SUMMARY
