# Return a semvar style tag based on the repos existing tags
name: "[Data - Parse] Semvar Tag"


on:
  workflow_call:
    outputs:
      tag:
        description: "Version Tag"
        value: ${{ jobs.create_tags.outputs.tag }}
      new_tag:
        description: "New Tag"
        value: ${{ jobs.create_tags.outputs.new_tag }}
    inputs:
      branch_name:
        type: string
        description: "Current Git branch name"
        required: true
      release_branch:
        type: string
        description: "Branch used for releases, defaults to main"
        default: "main"
        required: false

jobs:
  create_tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump version
        id: bump_version
        uses: anothrNick/github-tag-action@1.66.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INITIAL_VERSION: 0.0.1
          DEFAULT_BUMP: minor
          PRERELEASE_SUFFIX: ${{ inputs.branch_name }}
          RELEASE_BRANCHES: ${{ inputs.release_branch }}
          WITH_V: true
    outputs:
      tag: ${{ steps.bump_version.outputs.tag }}
      new_tag: ${{ steps.bump_version.outputs.new_tag }}
