# As matrix does not expose an index within the steps
# this will take an array and add an index to that data
# so can generate unique files etc
name: "[Data - Parse] Add Index"

on:
  workflow_call:
    inputs:
      original_list:
        description: 'String containing a JSON formated list. For example: ["api:latest", "front:latest"]'
        type: string
        required: true
    outputs:
      indexed_list:
        description: 'Updated list with each item containing an i attr for the index.'
        value: ${{ jobs.generate_indexed_version.outputs.indexed }}

permissions:
  contents: none
  security-events: none
  pull-requests: none
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none

jobs:
  generate_indexed_version:
    name: 'Use the tagged_images json to create a counter for safe files'
    runs-on: ubuntu-latest
    outputs:
      indexed: ${{ steps.add_index.outputs.indexed }}
    steps:
      - id: add_index
        run: |
          index_added=""
          i=0
          while read row; do
              object="{\"i\":\"${i}\",\"data\": ${row}}"
              index_added="${object_array}${object},"
              ((i=i+1))
          done << EOT
          $(jq -c '.[]' <<< ${{ inputs.original_list }}
          EOT

          echo "::set-output name=indexed::${index_added}"
