# Generate Terraform Workspace name
name: "[Data - Parse] Terraform Workspace Name"

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      name:
        description: 'Generated terraform workspace name.'
        value: ${{ jobs.generate_workspace_name.outputs.workspace_name }}

permissions:
  contents: read
  security-events: none
  pull-requests: none
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none

jobs:
  generate_workspace_name:
    name: 'Generate the terraform workspace name to use'
    runs-on: ubuntu-latest
    outputs:
      workspace_name: ${{ steps.workspace_name.outputs.trimmed }}
    steps:
      - id: branch_setup
        name: Setup branch variable
        run: |
          branch=${GITHUB_HEAD_REF}
          if [ -z "${GITHUB_HEAD_REF}" ]; then
            branch=${GITHUB_REF#refs/heads/}
          fi
          echo "branch=${branch}" >> $GITHUB_OUTPUT
      - id: workspace_name
        name: Generate workspace name
        uses: ministryofjustice/opg-github-actions/.github/actions/safe-strings@v1.2.0
        with:
          original: ${{steps.branch_setup.outputs.branch}}
          conditional_match: "main"
          conditional_value: "production"
          suffix: ${{ github.event.number }}
          length: 11

  results:
    name: 'Results'
    runs-on: ubuntu-latest
    needs: [generate_workspace_name]
    steps:
      - name: 'Summary'
        if: always()
        run: |
          echo "### Workspace Name Results" >> $GITHUB_STEP_SUMMARY
          echo "| Variable | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| workspace_name | ${{ needs.generate_workspace_name.outputs.workspace_name }} |"  >> $GITHUB_STEP_SUMMARY
