name: "[Linting - Infrastructure] Terraform Lint"


on:
  workflow_call:
    inputs:
      terraform_version:
        type: string
        description: "Version of terraform to use"
        required: true
      terraform_wrapper:
        type: boolean
        description: "Enable terraform wrapper"
        default: false
        required: false
      directory:
        type: string
        description: "Directory path to lint"
        default: "./terraform"
        required: false
      tflint_check:
        type: boolean
        description: "Enable tflint check"
        default: true
        required: false
      terraform_version_file:
        type: string
        description: "File containing the terraform version to use"
        required: false
        default: "NOT_SET"

jobs:
  terraform_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Terraform version
        id: tf_version
        env:
          TF_VERISON_FILE: ${{ inputs.terraform_version_file }}
          TF_VER: ${{ inputs.terraform_version }}
        run: |
          if [ "${TF_VERISON_FILE}" != "NOT_SET" ]; then
            echo "Using terraform version from file"
            if [ ! -f "${TF_VERISON_FILE}" ]; then
              echo "Terraform version file not found"
              exit 1
            fi
            echo "TF_VERSION=$(cat ${TF_VERISON_FILE)" >> $GITHUB_OUTPUT
          else
            echo "Using terraform version from input"
            echo "TF_VERSION=${TF_VER}" >> $GITHUB_OUTPUT
          fi
        shell: bash
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.tf_version.outputs.TF_VERSION }}
          terraform_wrapper: ${{ inputs.terraform_wrapper }}
      - name: "Run Terraform fmt"
        working-directory: ${{ inputs.directory }}
        run: terraform fmt -check -recursive  
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        if: ${{ inputs.tflint_check }}
      - name: "Run TFLint"
        working-directory: ${{ inputs.directory }}
        if: ${{ inputs.tflint_check }}
        run: tflint --recursive
