name: "[Linting - Infrastructure] Terraform Lint"


on:
  workflow_call:
    inputs:
      terraform_version:
        type: string
        description: "Version of terraform to use"
        required: true
      terraform_wrapper:
        type: boolean
        description: "Enable terraform wrapper"
        default: false
        required: false
      directory:
        type: string
        description: "Directory path to lint"
        default: "./terraform"
        required: false
      tflint_check:
        type: boolean
        description: "Enable tflint check"
        default: true
        required: false

jobs:
  terraform_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform_version }}
          terraform_wrapper: ${{ inputs.terraform_wrapper }}
      - name: "Run Terraform fmt"
        working-directory: ${{ inputs.directory }}
        run: terraform fmt -check -recursive
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        if: ${{ inputs.tflint_check }}
      - name: "Run TFLint"
        working-directory: ${{ inputs.directory }}
        if: ${{ inputs.tflint_check }}
        run: tflint --recursive
