name: "[Linting - Application] Pylint"


on:
  workflow_call:
    inputs:
      python_version:
        type: string
        description: "Version of python to use"
        default: "3.10.5"
        required: false
      directory:
        type: string
        description: "Directory path to lint"
        required: true

jobs:
  python_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Python version
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ inputs.python_version }}
      - name: Install pylint
        working-directory: ${{ inputs.directory }}
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Run pylint
        working-directory: ${{ inputs.directory }}
        run:
          find . -name '*.py' -exec pylint {} \;
