name: "[Docker] Prepare Snyk Image"

on:
  workflow_call:
    inputs:
      artifact_directory:
        type: string
        description: "Directory to store the Snyk image cache"
        default: "/tmp/images"
        required: false

      aws_region:
        type: string
        description: "AWS region"
        default: "eu-west-1"
        required: false

      oidc_role_to_assume:
        type: string
        description: "OIDC role to assume for pulling the Snyk image"
        required: true

      snyk_ecr_registry_id:
        type: string
        description: "AWS account ID for the ECR registry containing the Snyk image"
        required: true

      snyk_image:
        type: string
        description: "Snyk image reference"
        required: true

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash

jobs:
  prepare_snyk_image:
    name: Prepare Snyk Image
    runs-on: ubuntu-latest
    steps:
      - name: Restore Snyk Image Cache
        id: snyk_cache
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: ${{ inputs.artifact_directory }}/snyk-cache
          key: snyk_cache_${{ inputs.snyk_image }}

      - name: Configure AWS Credentials
        if: ${{ steps.snyk_cache.outputs.cache-hit != 'true' }}
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
        with:
          aws-region: ${{ inputs.aws_region }}
          mask-aws-account-id: "true"
          role-duration-seconds: 3600
          role-session-name: OPGDockerBuildGithubAction
          role-to-assume: ${{ inputs.oidc_role_to_assume }}

      - name: Login to ECR
        if: ${{ steps.snyk_cache.outputs.cache-hit != 'true' }}
        uses: aws-actions/amazon-ecr-login@03f1aad4c6c7ffd436567f42f9384779290529bd # v2.1.7
        with:
          registries: ${{ inputs.snyk_ecr_registry_id }}

      - name: Pull and Save Snyk Image
        if: ${{ steps.snyk_cache.outputs.cache-hit != 'true' }}
        env:
          AWS_REGION: ${{ inputs.aws_region }}
          SNYK_ECR_REGISTRY_ID: ${{ inputs.snyk_ecr_registry_id }}
          SNYK_IMAGE: ${{ inputs.snyk_image }}
          SNYK_CACHE_DIRECTORY: ${{ inputs.artifact_directory }}/snyk-cache
          SNYK_CACHE_PATH: ${{ inputs.artifact_directory }}/snyk-cache/snyk.tar
        run: |
          mkdir -p "${SNYK_CACHE_DIRECTORY}"
          SNYK_REGISTRY="${SNYK_ECR_REGISTRY_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
          docker pull "${SNYK_REGISTRY}/${SNYK_IMAGE}"
          docker save "${SNYK_REGISTRY}/${SNYK_IMAGE}" --output "${SNYK_CACHE_PATH}"
